baseURL = 'https://kfns0b11.github.io'
languageCode = 'en-us'
title = "kfns0b11's blog"
theme="archie"
copyright = "© kfn0b11"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "As long as we are alive, there is no bad end."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kfns0b11"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4