baseURL = 'https://kfns0b11.github.io/'
languageCode = 'en-us'
title = "kfns0b11's NoteBook"
theme="hugo-ink"
copyright = "© kfn0b11"
# Code Highlight
pygmentsstyle = "borland"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	avatar = "https://avatars.githubusercontent.com/u/88999483?v=4"
	mode="auto"
	useCDN=false
	subtitle = "Learn in public, the fast way to learn."
	favicon = "https://raw.githubusercontent.com/kfns0b11/kfns0b11.github.io/main/static/images/favicon.ico"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kfns0b11"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4