baseURL = "https://kfngp.github.io"
languageCode = "en-us"
title = "kfngp's blog "
theme = "cactus"
copyright = "kfngp" # cactus will use title if copyright is not set
disqusShortname = "kfngp" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Archive"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  logo = "https://imgns.oss-cn-beijing.aliyuncs.com/img/20210816155603.gif"
  description = "As long as we are alive, there is no bad end."
  mainSection = "posts" # your main section
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 10 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/kfngp?tab=repositories" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "gitalk" # more supported engines will be added.
  [params.comments.gitalk]
    clientID = "db571745319a8ad19f42" # Your client ID
    clientSecret = "c715cae53c48f23f37c8f4d8bd7c9f6035b5af58" # Your client secret
    repo = "kfngp.github.io" # The repo to store comments
    owner = "kfngp" # Your GitHub ID
    admin= "kfngp" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit c


  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/kfngp"
  # [[params.social]]
  #   name = "linkedin"
  #   link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "email"
    link = "kfnsjc@gmail.com"  # no need for "mailto:" in the head
